[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
movie_review = "2JnY2Fgxyv1bNq2dugGiMQTib3Wyxs8bszcX51tw3BtH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/eric/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
