[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "14sUS6ibSoXE6bLrFZGv1md1fRdpDu3Z2T4zfpB1UpU3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/eric/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
